# Generated by Django 3.0.7 on 2020-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20200302_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('no_of_users_rated', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=1000)),
                ('genres', models.TextField(max_length=1000)),
                ('images', models.CharField(max_length=10000)),
                ('cast', models.TextField(max_length=100000)),
                ('crew', models.TextField(max_length=100000)),
                ('reviews', models.TextField(max_length=100000)),
                ('recommendations', models.TextField(max_length=100000)),
                ('data', models.TextField(max_length=100000)),
            ],
        ),
    ]
