# Generated by Django 3.0.7 on 2020-06-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_moviedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='provider',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
