# Generated by Django 3.0.7 on 2020-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20200611_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='data',
            new_name='platforms',
        ),
        migrations.AddField(
            model_name='moviedata',
            name='platform_present',
            field=models.BooleanField(default=False),
        ),
    ]
