# Generated by Django 3.0.7 on 2020-06-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20200611_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='platform_present',
            new_name='platforms_present',
        ),
    ]
