# Generated by Django 3.0.7 on 2020-06-11 18:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_auto_20200611_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesData',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('no_of_users_rated', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=1000)),
                ('genres', models.TextField(max_length=1000)),
                ('seasons', models.IntegerField()),
                ('images', jsonfield.fields.JSONField(blank=True, null=True)),
                ('cast', jsonfield.fields.JSONField(blank=True, null=True)),
                ('crew', jsonfield.fields.JSONField(blank=True, null=True)),
                ('reviews', jsonfield.fields.JSONField(blank=True, null=True)),
                ('recommendations', jsonfield.fields.JSONField(blank=True, null=True)),
                ('platforms', jsonfield.fields.JSONField(null=True)),
                ('platforms_present', models.BooleanField(default=False)),
            ],
        ),
    ]
